theme: jekyll-theme-slate
title: Welcome to the Hello-World homepage for CR!
description: I will bookmark this page to further my learning
<div>what else can i do again</div>
<div>this is another attempt</br>
to understand hiw to do something</br>
anything</div>
